# Generated by Django 2.2.1 on 2019-05-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yb_app', '0002_board_iscomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
