# Generated by Django 2.2.1 on 2019-05-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yb_app', '0003_auto_20190524_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='user_id',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
